name: First workflow
on:
    push:
        branches: 
            - main
            - dev
            - test
    pull_request: 
        branches: 
            - main
            - dev
            - test
    workflow_dispatch: 
jobs:
    build_job:
        runs-on: windows-latest
        steps:
            - name: checkout step
              uses: actions/checkout@v3
            - name: Run an inline script
              run: |
                echo "I love to test and see for myself"
            - name: Create an ENV in powershell
              run: |
                "{powershell_env}={working}" >> $env:GITHUB_ENV
            - name: output the `$powershell_env
              run: |
               Write-Host "the value of `$powershell_env is : $env:powershell-env"
                  
